title: Diglactic Blog

google_analytics: UA-135017895-2

copy_text: 2021 Diglactic, LLC

# Root website URL used for RSS feed
url: https://blog.diglactic.com

baseurl: ""

permalink: /:title/

plugins: ["jekyll-feed"]

excerpt_separator   : "\n\n"
