title: Diglactic Newsroom

google_analytics: UA-135017895-2

copy_text: 2020 Diglactic

# Root website URL used for RSS feed
url: https://newsroom.diglactic.com

baseurl: ""

permalink: /:title/

plugins: ["jekyll-feed"]
